/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.wind.service.thrift.data;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2020-07-27")
public enum DataType implements org.apache.thrift.TEnum {
  BEIJING(0),
  CHINA(1),
  GLOBE(2);

  private final int value;

  private DataType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static DataType findByValue(int value) { 
    switch (value) {
      case 0:
        return BEIJING;
      case 1:
        return CHINA;
      case 2:
        return GLOBE;
      default:
        return null;
    }
  }
}
