mymongo:
  address: 192.168.204.137
  host: 27017
  database: covid-19
  container:
    beijing: Beijing_new
    china: China_new
    globe: Globe_new

myhadoop:
  home: E:\Develop\hadoop
  tmp: E:\Develop\hadoop\tmp